### ISSUE TITLE
Navitia Mobility Manager with Tisseo

### ISSUE THREAD

**Issue by asfram** [CanalTP/navitia-mobility-manager#10]
**Tisseo/PaonBundle Installation**

**1. PaonBundle Installation instructions https://github.com/Tisseo/PaonBundle#installation
 After composer update, problems below are displayed**:
  Problem 1
    - The requested package tisseo/boa-bundle could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package tisseo/boa-bridge-bundle could not be found in any version, there may be a typo in the package name.
  Problem 3
    - Installation request for tisseo/core-bundle dev-master -> satisfiable by tisseo/core-bundle[dev-master].
    - tisseo/core-bundle dev-master requires components/jquery ~1.11.1 -> satisfiable by components/jquery[1.11.1, 1.11.2, 1.11.3, 1.11.x-dev] but these conflict with your requirements or minimum-stability.

**2.  Adding BoaBundle and BoaBridgeBundle repositories in composer.json, problems below are displayed**:
Problem 1
- Installation request for tisseo/core-bundle dev-master -> satisfiable by tisseo/core-bundle[dev-master].
- tisseo/core-bundle dev-master requires components/jquery ~1.11.1 -> satisfiable by components/jquery[1.11.1, 1.11.2, 1.11.3, 1.11.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
- tisseo/core-bundle 1.2.x-dev requires components/jquery ~1.11.1 -> satisfiable by components/jquery[1.11.1, 1.11.2, 1.11.3, 1.11.x-dev] but these conflict with your requirements or minimum-stability.
- tisseo/boa-bundle dev-master requires tisseo/core-bundle ~1.2.0 -> satisfiable by tisseo/core-bundle[1.2.x-dev].
- Installation request for tisseo/boa-bundle dev-master -> satisfiable by tisseo/boa-bundle[dev-master].

**3. Set dev stabiliy flag for components/jquery, problems below are displayed**:
Problem 1
- Installation request for tisseo/core-bundle dev-master -> satisfiable by tisseo/core-bundle[dev-master].
- tisseo/core-bundle dev-master requires makeusabrew/bootbox dev-master -> satisfiable by makeusabrew/bootbox[dev-master] but these conflict with your requirements or minimum-stability.
  Problem 2
- tisseo/core-bundle 1.2.x-dev requires makeusabrew/bootbox dev-master -> satisfiable by makeusabrew/bootbox[dev-master] but these conflict with your requirements or minimum-stability.
- tisseo/boa-bundle dev-master requires tisseo/core-bundle ~1.2.0 -> satisfiable by tisseo/core-bundle[1.2.x-dev].
- Installation request for tisseo/boa-bundle dev-master -> satisfiable by tisseo/boa-bundle[dev-master].

**Comment by vincentlepot** [comment]
I don't think this should be registered here since it regards Tisseo's bundle...

**Comment by tchevily** [comment]
The issue comes from other bundle
